# Numpy
Numerical Python library for **LINEAR ALGEBRA** 

**Conda install numpy**

In [2]:
# Required Imports
import numpy
import numpy as np

### NUMPY BASICS

In [ ]:
a=np.array([1,2,3,4]) #creates an array
print(a.shape) #prints size of the array "(rows,columns)", as this has only one row so (rows,) NOTE : See it in ROW WAY 
print(type(a))
print(a[0])
a[0]=5
print(a)

In [ ]:
a=np.array([[2,3],[4,1],[1,6],[4,5]])
print(a.shape)
print(a)

In [ ]:
a=np.array([[2,3,5,6],[4,1,5,6]])
print(a.shape)
print(a)

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)
print(a)
print(a[0,2])
print(a[1,1])

In [ ]:
a=np.array([[1,1,1,1],[2,2,2,2],[4,5,7,5]])
print(a.shape)
print("------------------")
print(a[: , :]) #print entire matrix 
print("------------------")
print(a[:]) 
print("------------------")
print(a[2]) #print a row
print("------------------")
print(a[:,2]) # print only 3nd column

In [ ]:
list1 = [[1,1,1,1],[2,2,2,2],[4,5,7,5]]
a=np.array(list1)
print(a)


In [ ]:
list1=[1,2,3,4]
list2 = [[1,2,3,4],[5,6,7,8]]

c=np.array(list1)
d=np.array(list2)

print(c)
print("------------------")
print(d)


### Reshape function
While changing array we should keep in mind : no of elements

In [ ]:
list1=[x for x in range(1,11)]
b=np.array(list1)
print(b)
print("------------------")

a=b.reshape(2,5)
print(a)
print("------------------")

c=a.reshape(-5,2) # ignores -ve sign and see the neat +ve value that will hold all elements 
print(c)
print("------------------")

d=a.reshape(-5,2) # ignores -ve sign
print(d)
print("------------------")

d=a.reshape(9,-2) # Cannot reshape  lol ! (3,2) DUDE check if it fits the complete array or not
#Factorial
print(d)

### Ravel Function

converts a 2D to 1D (xD --> 1D )

In [ ]:
# arange ==> 0-7 values
arr = np.arange(8)
print(arr)
print("------------------")

arr = arr.reshape(2,4) # Convert to 2D Array
print(arr)
print("------------------")
# arr = np.arange(8).reshape(2,4)  << single line

print(arr.ravel())  #convert to 1D array


### Tuple To Numpy

In [ ]:
# ndarray from exisisting data or tuple

tuple1 = (1,2,3,4)
print(type(tuple1))
e = np.array(tuple1)
print(e.shape)
print(e)

### Custom Matrix

In [ ]:
# Data Type conversion

x=[1,3,4]
a = np.array(x,dtype=float) # default 64 bit representation of float64
print(a)

In [ ]:
# Create  a array of all zeros (0's)

d = np.zeros((2,2),  dtype = np.float32) #creates a array of zeroes with float32 bit representation
#note if no float32 or no any type mentioned >>> it takes Float64 values >> useful for operations(best case ) 
print(d)
print(type(d[0,0]))


In [ ]:
# create an array of 1's

e=np.ones((2,2))
print(e)
print(type(e[0,0]))

In [3]:
# full matrix with our VALUE
e=np.full((3,4),7)
print(e)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#Identity matrix
# NOTE : It is always a square matrix so 1 values sent >> Default float
d = np.eye(3)
print(d)

In [ ]:
#Identity matrix with int type
d = np.eye((3), dtype = int)
print(d)

In [ ]:
#Random values matrix ( min_val, max_val, size=(x,y) )

d = np.random.randint(62,88, size=(3,4))
print(d)

In [ ]:
#note converting will not ROUND THE VALUE it will TRUNCATE DECIMAL VALUE
x = np.array([[7.6464654,4.54654545],[4.5465564654,4.654654]], dtype=int)
print(x)

## Array Indexing
numpy offers several ways to index into arrays.

similar to pyhton lists. but  specify to each dimension

### Positive indexing

In [ ]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b = a[:2,1:3]
print("---------------------")
print(b)

### Negative Indexing


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print("---------------------")
b = a[:-2, :-1]  # DUDEEEE upto "UPTO ****" -2 means it is not inclue -2 row index
print(b)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,12,12]])
print(a)
print("---------------------")
print(a[1:])

In [8]:
#a's address copied to b's address 
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,12,12]])
print("a=\n",a)
b= a
print("------------ changed b[1][2]=99")
b[1][2]=99
print("a=\n",a)
print("b=\n",b)

a=
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 12]]
------------ changed b[1][2]=99
a=
 [[ 1  2  3]
 [ 4  5 99]
 [ 7  8  9]
 [10 12 12]]
b=
 [[ 1  2  3]
 [ 4  5 99]
 [ 7  8  9]
 [10 12 12]]


In [ ]:
#a's address copied to b's address as the given format[:2,1:3]
#what ever changes made to the b's positions will reflect to a's array at that place where b has ccopied the values

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,12,12]])
print("a=\n",a)
b= a[:2,1:3]
print("b=\n",b)
print("--------------------- the a's value a[0,1] changed = 2")
print(a[0,1])
b[0,0]=77
print("--------------------- changed value of b[0,0]")
print(a[0,1])
print("--------------------- b's [0,0] == a's [0,2] ")
print("a=\n",a)
print("SO, places indices are not changing")

## Arange function


In [ ]:
# range(start,end,step) Step can be float 
a = np.arange(2,10,0.15)
print(a)
print("-----------------")
a = np.arange(2,10,0.1)
print(a)
print("-----------------")


In [ ]:
#SLICES

a = np.arange(2,10,0.1)
print(a)
print("-----------------")

s = slice(10,20,2) # slice() << select only specific indices 
#slice(start_index, End_Index, Step)
print(a[s])

### Acessing specific values in differenent rows and and differnt column values

numbers of one array passed as index to next array

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print("--------------------- b's array")
b = np.array([0,2,1,0])
print(b)
print("--------------------- a's array by b's index")
print(a[np.arange(4),b]) #arange function
print("---------------------")
a[np.arange(4),b]+=10 #selected updation of elements from a matrix
print(a)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b = np.array([0,2,0,1])
print("____________")
print(a[np.arange(4),b])


## Advanced Indexing

In [ ]:
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,4],[10,11,12,45]])
print(a)
b = a[0:2,1:3]
c = a[0:2,[1,3]]
print(b)
print(c)

## Boolean Indexing


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
y=(a>5) # returns 2D array of BOOLEAN of x's array which satisfies the conditions
z=a[a>5] # returns 1D array with elemnts in x who satisfies the condition
print(y)
print(z)


## Array Math


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[1,2],[3,4]], dtype=np.float64)


#Element wise operation
print(x+y)
print(np.add(x,y))
print("---------------------")

print(x-y)
print(np.subtract(x,y))
print("---------------------")

print(x*y)
print(np.multiply(x,y))
print("---------------------")

print(x/y)
print(np.divide(x,y))
print("---------------------")

print(np.sqrt(x))


#tra

apart from coputing mathematical functions using, we frequently need to  reshape or otherwise manipulate data in arrays. the simplest example ofthis type of operation is transposing a matrix; to transpose a matrix simply use T attribure o an array object

In [ ]:
#Transpose a matrix

x = np.array([[1,2],[3,4]])
print(x)
print(x.T)

# Exercise

## Problem 7:
Heads and legs puzzle

we count x heads and y legs among the chickens, rabbits, and snakes in a farm . how many rabbits, chickens and snakes do we have ?


In [ ]:
# heads = int(input("Enter No Of Heads"))
# legs = int(input("Enter No Of Legs"))

# cr_heads = int(legs/2)
# s_heads = 0

# heads_by_legs=cr_heads+s_heads

# if heads_by_legs < heads:
#     diff_heads = heads_by_legs - heads
#     c_r=c_r-(diff_heads/2)
# ### NOT the GOOD WAY TO THINK

In [1]:
def cal(h,l,c,r,s):
    if h==0 and l==0:
        print("C = {0} Rabbits= {1} s= {2}".format(c,r,s))
        return
    elif h==0 and l!=0:
        return       
    else:
        cal(h-1,l,c,r,s+1)
        cal(h-1,l-2,c+1,r,s)
        cal(h-1,l-4,c,r+1,s)
        
        
heads = int(input("Enter No Of Heads"))
legs = int(input("Enter No Of Legs"))
cal(heads,legs,0,0,0)

Enter No Of Heads7
Enter No Of Legs12
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 4 Rabbits= 1 s= 2
C = 4 Rabbits= 1 s= 2
C = 2 Rabbits= 2 s= 3
C = 4 Rabbits= 1 s= 2
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 4 Rabbits= 1 s= 2
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 4 Rabbits= 1 s= 2
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2 s= 3
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 0 Rabbits= 3 s= 4
C = 2 Rabbits= 2 s= 3
C = 2 Rabbits= 2

In [4]:
###### Updated Version

# Global array
comb=[]

def addcomb(c,r,s):
    for i in range(len(comb)):
        if comb[i][0]==c and comb[i][1]==r and comb[i][2]==s:
            return
    comb.append([c,r,s])
    return

def cal(h,l,c,r,s):
    if h==0 and l==0:
        addcomb(c,r,s)
        return
    elif h==0 and l!=0:
        return       
    else:
        cal(h-1,l,c,r,s+1)
        cal(h-1,l-2,c+1,r,s)
        cal(h-1,l-4,c,r+1,s)
        

heads = int(input("Enter No Of Heads"))
legs = int(input("Enter No Of Legs"))


print("\nPossible combinations are :")
cal(heads,legs,0,0,0)

# print(np.array(comb))

for animal in comb:
    print("Chickens : {0} Rabbits: {1} Snakes: {2}".format(animal[0],animal[1],animal[2]))
    


Enter No Of Heads7
Enter No Of Legs12

Possible combinations are :
Chickens : 0 Rabbits: 3 Snakes: 4
Chickens : 2 Rabbits: 2 Snakes: 3
Chickens : 4 Rabbits: 1 Snakes: 2
Chickens : 6 Rabbits: 0 Snakes: 1


## Problem 8

Matrix multiplication

In [1]:
import numpy as np
r1=int(input("Enter row of matrix-1 : "))
c1=int(input("Enter column of matrix-1 : "))

r2=int(input("Enter row of matrix-2 : "))
c2=int(input("Enter column of matrix-2 : "))

m1=[]
m2=[]
ans=[]
if r1==c2:
    print("Enter values for matrix-1 :")
    for x in range(r1):
        t=[]
        for y in range(c1):
            k=int(input("Val: "))
            t.append(k)
        m1.append(t)   
        
    print("Enter values for matrix-2 :")
    
    for x in range(r2):
        t=[]
        for y in range(c2):
            k=int(input("Val: "))
            t.append(k)
        m2.append(t)
        
    
    print(np.dot(np.array(m1),np.array(m2)))
    
else:
    print("Wrong Dimensions !")

Enter row of matrix-1 : 3
Enter column of matrix-1 : 3
Enter row of matrix-2 : 3
Enter column of matrix-2 : 3
Enter values for matrix-1 :
Val: 234
Val: 3
Val: 4
Val: 5
Val: 6
Val: 2
Val: 3
Val: 4
Val: 4
Enter values for matrix-2 :
Val: 3
Val: 4
Val: 5
Val: 1
Val: 2
Val: 34
Val: 5
Val: 3
Val: 2
[[ 725  954 1280]
 [  31   38  233]
 [  33   32  159]]


### Problem 9
List compresnsion Identity matrix

In [ ]:
# import numpy as np

# list1=[]

# for i in range(4):
#     for j in range(4):
#         t=[]
#         x=0
#         if i==j:
#             x=1
#         t.append(x)       
#     list1.append(t)

In [2]:
import numpy as np
n=int(input("Enter rows for matrix"))
print(np.array([[1 if i==j else 0 for j in range(n)] for i in range(n)] ))

Enter rows for matrix10
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
