In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
print(a.shape)
print(a)

(4,)
[1 2 3 4]


In [8]:
a = np.array([[1,2,3,],[4,54,5]])
print(a)

[[ 1  2  3]
 [ 4 54  5]]


In [12]:
print(a[::,2])

[3 5]


In [14]:
np.array(a, dtype=np.float32)

array([[ 1.,  2.,  3.],
       [ 4., 54.,  5.]], dtype=float32)

In [4]:
list=[1,2,5,3,5,6,1.0,'sadas']
print(list)

[1, 2, 5, 3, 5, 6, 1.0, 'sadas']
